### ISSUE TITLE
No terminal on Raspberry Pi

### ISSUE THREAD

**Issue by snozzlebert** [hassio-addons/addon-ide#2]
# Problem/Motivation

Terminal doesn't load. Loader keeps spinning.

## Expected behavior

Available terminal.

## Actual behavior

No terminal available and the following errors in the log:

```
{ Error: Cannot find module '../build/Release/pty.node'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/.c9/node_modules/pty.js/lib/pty.js:9:11)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3) code: 'MODULE_NOT_FOUND' } '/root/.c9/node_modules/pty.js'
{ Error: Cannot find module 'pty.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /cloud9/node_modules/vfs-local/localfs.js:85:23
    at Array.some (native)
    at setup (/cloud9/node_modules/vfs-local/localfs.js:83:36)
    at Object.<anonymous> (/cloud9/node_modules/vfs-child/child.js:5:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10) code: 'MODULE_NOT_FOUND' } 'pty.js'
{ Error: Cannot find module 'pty.nw.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at /cloud9/node_modules/vfs-local/localfs.js:85:23
    at Array.some (native)
    at setup (/cloud9/node_modules/vfs-local/localfs.js:83:36)
    at Object.<anonymous> (/cloud9/node_modules/vfs-child/child.js:5:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10) code: 'MODULE_NOT_FOUND' } 'pty.nw.js'
unable to initialize pty.js:
PTY is not supported.
PTY is not supported.
PTY is not supported.
```

## Steps to reproduce

Install and start the addon on a Raspberry Pi 2.

**Comment by frenck** [comment]
This is a confirmed bug when running the add-on on ARM based machines (like the Pi's).
Looking into a way of fixing this.

**Comment by frenck** [comment]
Found some references:

https://github.com/c9/core/issues/197
https://github.com/chintanp/Cloud9-on-RPi/blob/master/c9_bash_RPi.sh

<blockquote><img src="https://avatars3.githubusercontent.com/u/752869?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/chintanp/Cloud9-on-RPi">chintanp/Cloud9-on-RPi</a></strong></div><div>Cloud9-on-RPi - Stuff related to development on RPi using Cloud9 etc.</div></blockquote>

**Comment by frenck** [comment]
I'm sorry to say, but arm(32/64) support has been dropped.

Therefore, this issue is no longer relevant.

**Comment by JohanLeirnes** [comment]
Huh?? why not support arm anymore!

**Comment by frenck** [comment]
@bhaap For more information, please read the official announcement:

https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck

<blockquote><img src="https://community.home-assistant.io/user_avatar/community.home-assistant.io/frenck/200/13184_1.png" width="48" align="right"><div><img src="https://community.home-assistant.io/uploads/default/original/1X/510301398ed5188e395eafb0983fbf8fe8ffcbcf.png" height="14"> Home Assistant Community</div><div><strong><a href="https://community.home-assistant.io/t/community-hass-io-add-on-ide-based-on-cloud9/33810/57?u=frenck">Community Hass.io Add-on: IDE, based on Cloud9</a></strong></div><div>🎉 Release v0.2.0 This release is exciting, at least, for me it is. I’ve been working on this for months! And for you? Well, a couple of things…  So what did change? I’ve updated the workflows of the Community Hass.io Add-ons project. Things include:   Replaced CircleCI and CodeClimate. We are now using GitLab CI, backed by a couple of custom servers building and testing these add-ons. All add-ons are now scanned during built and release by Clair to prevent security issues in our add-ons. A...</div></blockquote>
