### ISSUE TITLE
IDE can't start with kaefer package error

### ISSUE THREAD

**Issue by UksusoFF** [hassio-addons/addon-ide#20]
Just install addon on RPI 3 with Home Assistant 0.77.3 and run it. 

Log: 
```Connect server listening at http://127.0.0.1:80
Using basic authentication
CDN: version standalone initialized /cloud9/build
Trace: Error while starting '/cloud9/configs/standalone':
    at /cloud9/server.js:223:25
    at Architect.done (/cloud9/node_modules/architect/architect.js:410:9)
    at Architect.emit (events.js:180:13)
    at startPlugins (/cloud9/node_modules/architect/architect.js:296:21)
    at startPlugins (/cloud9/node_modules/architect/architect.js:301:21)
    at register (/cloud9/node_modules/architect/architect.js:327:13)
    at Server.<anonymous> (/cloud9/node_modules/connect-architect/connect/connect-plugin.js:135:13)
    at Object.onceWrapper (events.js:272:13)
    at Server.emit (events.js:180:13)
    at emitListeningNT (net.js:1373:10)
{ SyntaxError: Error parsing /cloud9/node_modules/kaefer/package.json: Unexpected token f in JSON at position 1
    at JSON.parse (<anonymous>)
    at readPackage (internal/modules/cjs/loader.js:137:52)
    at tryPackage (internal/modules/cjs/loader.js:147:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:229:20)
    at Module._resolveFilename (internal/modules/cjs/loader.js:546:25)
    at Function.modules._resolveFilename (/cloud9/node_modules/c9/setup_paths.js:27:16)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/cloud9/plugins/c9.vfs.server/vfs.js:5:14)
  path: '/cloud9/node_modules/kaefer/package.json',
  plugin: 
   { packagePath: '/cloud9/plugins/c9.vfs.server/vfs.connect.standalone.js',
     workspaceDir: '/workspace',
     readonly: undefined,
     extendDirectory: '/cloud9/settings/../plugins',
     extendOptions: { user: [Object], project: [Object], readonly: false },
     installPath: '/root/.c9',
     settingDir: undefined,
     collab: false,
     nakBin: '/cloud9/node_modules/nak/bin/nak',
     nodeBin: [ '/root/.c9/node/bin/node', '/usr/bin/node' ],
     tmuxBin: '/root/.c9/bin/tmux',
     vfs: 
      { defaultEnv: [Object],
        local: undefined,
        debug: false,
        inProcess: false },
     provides: [ 'vfs.connect' ],
     consumes: [ 'Plugin', 'api' ],
     setup: { [Function: main] consumes: [Array], provides: [Array] } } } 'SyntaxError: Error parsing /cloud9/node_modules/kaefer/package.json: Unexpected token f in JSON at position 1\n    at JSON.parse (<anonymous>)\n    at readPackage (internal/modules/cjs/loader.js:137:52)\n    at tryPackage (internal/modules/cjs/loader.js:147:13)\n    at Function.Module._findPath (internal/modules/cjs/loader.js:229:20)\n    at Module._resolveFilename (internal/modules/cjs/loader.js:546:25)\n    at Function.modules._resolveFilename (/cloud9/node_modules/c9/setup_paths.js:27:16)\n    at Function.Module._load (internal/modules/cjs/loader.js:475:25)\n    at Module.require (internal/modules/cjs/loader.js:598:17)\n    at require (internal/modules/cjs/helpers.js:11:18)\n    at Object.<anonymous> (/cloud9/plugins/c9.vfs.server/vfs.js:5:14)'
INFO: Starting the C9 server
```

**Comment by frenck** [comment]
Could you please provide some more information (as listed in the startup banner of the add-on?)

**Comment by UksusoFF** [comment]
@frenck 0.5.1 version

Config:
```
{
  "log_level": "info",
  "username": "***",
  "password": "***",
  "ssl": false,
  "certfile": "fullchain.pem",
  "keyfile": "privkey.pem",
  "packages": [],
  "init_commands": []
}
```

**Comment by UksusoFF** [comment]
Reinstall with latest version addon and hass fixed this trouble.
